{
 "title": "Instance_dashboard_2",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "RAM utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes-node_memory_MemAvailable_bytes)/node_memory_MemTotal_bytes*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk io time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Receive and Transmit Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(node_network_receive_errs_total[2m]) / rate(node_network_receive_packets_total[2m])",
     "legendFormat": "rc{{instance}}"
    },
    {
     "expr": "rate(node_network_transmit_errs_total[2m]) / rate(node_network_transmit_packets_total[2m])",
     "legendFormat": "tx{{instance}}"
    }
   ]
  },
  {
   "title": "Disk usage space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{fstype=\"ext4\"} * 100) / node_filesystem_size_bytes{fstype=\"ext4\"})",
     "legendFormat": "{{instance}}{{device}}"
    }
   ]
  },
  {
   "title": "Network receive and transmit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{device!=\"lo\"}[1m])",
     "legendFormat": "tx{{instance}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device!=\"lo\"}[1m])",
     "legendFormat": "rc{{instance}}"
    }
   ]
  },
  {
   "title": "Filesystem errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "node_filesystem_device_error{device!~\"none|tmpfs\"}",
     "legendFormat": "{{instance}}{{device}}"
    }
   ]
  },
  {
   "title": "Network saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "(rate(node_network_receive_bytes_total{device!~\"^tap.*|^vnet.*|^veth.*|^tun.*\"}[1m]) + rate(node_network_transmit_bytes_total{device!~\"^tap.*|^vnet.*|^veth.*|^tun.*\"}[1m])) / node_network_speed_bytes{device!~\"^tap.*|^vnet.*|^veth.*|^tun.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "http_response_size_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": " sum(increase(nginx_http_response_size_bytes[1m])) by (status,instance)",
     "legendFormat": "{{instance}} {{status}}"
    }
   ]
  },
  {
   "title": "http_response_count_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(increase(nginx_http_response_count_total[1m])) by (status,instance)",
     "legendFormat": "{{instance}} {{status}}"
    }
   ]
  }
 ]
}