- name: Download Elasticsearch
  get_url:
      url: https://storage.yandexcloud.net/drugov/ELK7/elasticsearch-7.17.8-amd64.deb?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=YCAJEAvqBdVwYwsmpSHOunfAn%2F20230122%2Fru-central1%2Fs3%2Faws4_request&X-Amz-Date=20230122T144633Z&X-Amz-Expires=2592000&X-Amz-Signature=6C7FFDEAED5CC06350AA603087D6F612840D5A4561F65373B80D4EAEE02B826F&X-Amz-SignedHeaders=host
      dest: /home/drogaps/

- name: Install  Java
  apt:
    update_cache: yes
    name: default-jdk
    install_recommends: no

- name: Install  Elasticsearch
  apt:
    update_cache: yes
    deb: /home/drogaps/elasticsearch-7.17.8-amd64.deb

- name: delete default config elastic.yml
  ansible.builtin.file:
    path: /etc/elasticsearch/elasticsearch.yml
    state: absent

- name: elastic new config file
  template:
    src: el-config.j2
    dest: /etc/elasticsearch/elasticsearch.yml

- name: change group elastic
  shell: chown root:elasticsearch /etc/elasticsearch/elasticsearch.yml
  notify: start Elasticsearch

#- name: start Elasticsearch
#  service:
#    name: elasticsearch
#    enabled: yes
#    state: started